#!/usr/bin/env node

// Fetches NSE prices, history, company details and news, then regenerates the site.
//
//   node update-stocks.js                 normal run: listing + news + a few detail refreshes
//   node update-stocks.js --render-only   rebuild pages from data/ without fetching
//   node update-stocks.js --backfill      fetch company page + price history for every
//                                         ticker (slow: ~2 min per ticker), no rendering
//   node update-stocks.js --details=N     refresh N tickers' details this run (default 6)

const fs = require('fs');
const https = require('https');

const afx = require('./lib/afx');
const { sectorSlug } = require('./lib/sectors');

const SITE = JSON.parse(fs.readFileSync('data/site.json', 'utf8'));
const UNIVERSE = JSON.parse(fs.readFileSync('data/universe.json', 'utf8'));
const STOCKS = UNIVERSE.stocks.map(s => s.symbol);
const STOCK_INFO = Object.fromEntries(UNIVERSE.stocks.map(s => [s.symbol, s]));

const MARKET_FILE = 'data/market.json';
const HISTORY_DIR = 'data/history';
const DETAILS_DIR = 'data/details';
const SECTOR_DIR = 'data/sectors';
const PAGES_DIR = 'stocks';
const SECTOR_PAGES_DIR = 'sectors';
const GENERATED_MARKER = '<!-- Generated by update-stocks.js';

// afx.kwayisi.org's robots.txt asks for 60 seconds between requests. The listing is one
// request; company pages and charts are two per ticker, so only a few are refreshed per run.
const CRAWL_DELAY_MS = 60_000;
const DEFAULT_DETAILS_PER_RUN = 6;
const USER_AGENT = `Mozilla/5.0 (compatible; NairobiStockDigest/1.0; +${SITE.url})`;

const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

function fetchRaw(url, timeoutMs = 30_000) {
  return new Promise((resolve, reject) => {
    const follow = (u, hops = 0) => {
      const req = https.get(u, { headers: { 'User-Agent': USER_AGENT } }, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location && hops < 5) {
          res.resume();
          return follow(new URL(res.headers.location, u).toString(), hops + 1);
        }
        if (res.statusCode !== 200) {
          res.resume();
          return reject(new Error(`HTTP ${res.statusCode} for ${u}`));
        }
        let data = '';
        res.setEncoding('utf8');
        res.on('data', (chunk) => { data += chunk; });
        res.on('end', () => resolve(data));
      });
      req.setTimeout(timeoutMs, () => req.destroy(new Error(`Timeout fetching ${u}`)));
      req.on('error', reject);
    };
    follow(url);
  });
}

async function withRetry(fn, attempts = 3, delayMs = 5000) {
  for (let i = 1; ; i++) {
    try {
      return await fn();
    } catch (err) {
      if (i >= attempts) throw err;
      await sleep(delayMs * i);
    }
  }
}

// ---------- News (Google News RSS, Kenya edition) ----------

// Search phrase for a company: the listed name without "Ltd"/"Plc", unless universe.json
// gives a better one in `news` (e.g. a brand name the press actually uses)
const newsQuery = (info) => info.news || info.name.replace(/\b(Ltd|Plc|Limited|PLC)\b\.?/g, '').replace(/\s+/g, ' ').trim();

function parseGoogleNews(xml, max = 12) {
  const items = [];
  for (const m of xml.matchAll(/<item>([\s\S]*?)<\/item>/g)) {
    if (items.length >= max) break;
    const item = m[1];
    const title = afx.decodeEntities((item.match(/<title><!\[CDATA\[(.*?)\]\]><\/title>/) || item.match(/<title>(.*?)<\/title>/))?.[1] || '');
    const url = (item.match(/<link>(.*?)<\/link>/) || [])[1];
    const pubDate = (item.match(/<pubDate>(.*?)<\/pubDate>/) || [])[1];
    const source = afx.decodeEntities((item.match(/<source[^>]*>(.*?)<\/source>/) || [])[1] || 'Google News');
    const date = pubDate && !isNaN(new Date(pubDate)) ? new Date(pubDate).toISOString() : null;
    if (title && url && date) items.push({ title: cleanNewsTitle(title, source), source, date, url });
  }
  return items;
}

// Google News titles end with " - <source>", which the pages already show separately
function cleanNewsTitle(title, source) {
  const suffix = ` - ${source}`;
  return title.toLowerCase().endsWith(suffix.toLowerCase()) ? title.slice(0, -suffix.length).trim() : title;
}

// Quote pages, "live" tickers and share-price listicles rather than news
const LOW_VALUE_NEWS = [
  /stock price,? news,? quote/i,
  /\bshare price (today|live)\b/i,
  /\b(stock|share) (forecast|prediction)\b/i,
  /\bNSE:\w+ stock quote\b/i
];
const isLowValueNews = (item) => LOW_VALUE_NEWS.some(re => re.test(item.title));

async function getNews(info) {
  const q = encodeURIComponent(`"${newsQuery(info)}"`);
  try {
    const xml = await fetchRaw(`https://news.google.com/rss/search?q=${q}&hl=en-KE&gl=KE&ceid=KE:en`);
    const items = parseGoogleNews(xml).filter(n => !isLowValueNews(n));
    const unique = [...new Map(items.map(n => [n.title, n])).values()];
    return unique.sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 6);
  } catch (err) {
    console.warn(`    ⚠️  News failed for ${info.symbol}: ${err.message}`);
    return null;
  }
}

// ---------- Price history ----------

const round2 = (n) => (n == null ? null : Math.round(n * 100) / 100);

function readHistory(symbol) {
  const file = `${HISTORY_DIR}/${symbol.toLowerCase()}.json`;
  return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : [];
}

// One [date, close] row per line, so each day's commit only adds a line or two
function writeHistory(symbol, rows) {
  fs.mkdirSync(HISTORY_DIR, { recursive: true });
  fs.writeFileSync(`${HISTORY_DIR}/${symbol.toLowerCase()}.json`, `[\n${rows.map(r => JSON.stringify(r)).join(',\n')}\n]\n`);
}

// Union of two [date, close] series by date; `newer` wins on the same date
function mergeHistory(older, newer) {
  const byDate = new Map(older.map(r => [r[0], r]));
  for (const r of newer) byDate.set(r[0], r);
  return [...byDate.values()].sort((a, b) => a[0].localeCompare(b[0]));
}

// Trading date (Nairobi time) of a listing timestamp
const nairobiDate = (iso) => new Date(iso).toLocaleDateString('en-CA', { timeZone: 'Africa/Nairobi' });

// ---------- Returns ----------

function daysAgo(now, n) {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d;
}

function monthsAgo(now, n) {
  const d = new Date(now);
  d.setMonth(d.getMonth() - n);
  return d;
}

// Periods shown on the dashboard; 1D comes straight from the listing
const RETURN_PERIODS = {
  fiveDay: (now) => daysAgo(now, 7),  // 7 calendar days covers 5 trading days
  oneMonth: (now) => monthsAgo(now, 1),
  sixMonth: (now) => monthsAgo(now, 6),
  ytd: (now) => new Date(Date.UTC(now.getUTCFullYear() - 1, 11, 31)),  // last close of prior year
  oneYear: (now) => monthsAgo(now, 12),
  threeYear: (now) => monthsAgo(now, 36),
  fiveYear: (now) => monthsAgo(now, 60),
  tenYear: (now) => monthsAgo(now, 120)
};

// % return for each period, measured from the latest close on or before its start date.
// A start before the stock's first close gives null (history doesn't reach back that far).
// `history` is [[date, close]] oldest → newest.
function returnsFromHistory(history, price, now = new Date()) {
  const out = {};
  for (const [field, getStart] of Object.entries(RETURN_PERIODS)) {
    const start = getStart(now).toISOString().slice(0, 10);
    let past = null;
    for (const [date, close] of history) {
      if (date <= start) past = close;
      else break;
    }
    out[field] = past && price != null ? round2(((price - past) / past) * 100) : null;
  }
  return out;
}

// Evenly spaced subset of `rows` (always keeping the last row), at most `max` points
function downsample(rows, max) {
  if (rows.length <= max) return rows;
  const step = (rows.length - 1) / (max - 1);
  return Array.from({ length: max }, (_, i) => rows[Math.round(i * step)]);
}

// Homepage sparklines: closes since each period's start, ending at the current price
function sparklines(history, price, now = new Date()) {
  if (!history.length) return null;
  const out = {};
  for (const [field, getStart] of Object.entries(RETURN_PERIODS)) {
    const start = getStart(now).toISOString().slice(0, 10);
    if (history[0][0] > start) continue;
    const rows = history.filter(r => r[0] >= start);
    out[field] = [...downsample(rows, 40).map(r => r[1]), price].filter(v => v != null);
  }
  return out;
}

// Profile chart: daily closes for the last year, weekly before that
function chartSeries(history, now = new Date()) {
  const yearAgo = monthsAgo(now, 12).toISOString().slice(0, 10);
  return {
    daily: history.filter(r => r[0] >= yearAgo),
    weekly: history.filter((r, i) => r[0] < yearAgo && i % 5 === 0)
  };
}

// ---------- Company details (company page + chart, refreshed a few per run) ----------

function readDetails(symbol) {
  const file = `${DETAILS_DIR}/${symbol.toLowerCase()}.json`;
  return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : null;
}

// Tickers whose details are missing or oldest come first
function pickDetailTickers(symbols, fetchedAt, n) {
  return [...symbols]
    .sort((a, b) => (fetchedAt[a] || '').localeCompare(fetchedAt[b] || '') || a.localeCompare(b))
    .slice(0, n);
}

async function refreshDetails(symbol, isFirst) {
  if (!isFirst) await sleep(CRAWL_DELAY_MS);
  const page = await withRetry(() => fetchRaw(afx.companyUrl(symbol)));
  const details = { ...afx.parseCompany(page), fetchedAt: new Date().toISOString() };
  await sleep(CRAWL_DELAY_MS);
  const chart = afx.parseChart(await withRetry(() => fetchRaw(afx.chartUrl(symbol))));
  if (chart.length) writeHistory(symbol, mergeHistory(readHistory(symbol), chart));
  fs.mkdirSync(DETAILS_DIR, { recursive: true });
  fs.writeFileSync(`${DETAILS_DIR}/${symbol.toLowerCase()}.json`, JSON.stringify(details, null, 2) + '\n');
  console.log(`    ✓ ${symbol}: details + ${chart.length} days of history`);
}

async function refreshSomeDetails(symbols, n) {
  const fetchedAt = Object.fromEntries(symbols.map(s => [s, readDetails(s)?.fetchedAt]));
  const picked = pickDetailTickers(symbols, fetchedAt, n);
  console.log(`Refreshing details for ${picked.length} ticker(s): ${picked.join(', ')}`);
  for (const [i, symbol] of picked.entries()) {
    try {
      await refreshDetails(symbol, i === 0);
    } catch (err) {
      console.warn(`    ⚠️  Details failed for ${symbol}: ${err.message}`);
    }
  }
}

// Valuation from the latest price: EPS/DPS/shares change only with results, but P/E,
// yield and market cap move with the price every day
function valuation(details, price) {
  if (!details || price == null) return { pe: null, dividendYield: null, marketCap: null };
  return {
    pe: details.eps > 0 ? round2(price / details.eps) : null,
    dividendYield: details.dps != null ? round2((details.dps / price) * 100) : null,
    marketCap: details.sharesOutstanding ? Math.round(details.sharesOutstanding * price) : null
  };
}

// ---------- Build + render ----------

function readPreviousData() {
  try {
    return JSON.parse(fs.readFileSync(MARKET_FILE, 'utf8'));
  } catch (err) {
    return { market: null, stocks: {} };
  }
}

// "Sep 23, 2026, 6:13 PM EAT": when the NSE prices were published
function dataTimeLabel(iso) {
  if (!iso) return '—';
  return new Date(iso).toLocaleString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit', timeZone: 'Africa/Nairobi'
  }) + ' EAT';
}

// Put arrays of plain numbers (sparkline points) on one line
const compactNumberArrays = (json) => json.replace(/\[\s*(-?[\d.e+-]+(?:,\s*-?[\d.e+-]+)*)\s*\]/g, (m, nums) => `[${nums.replace(/\s+/g, '')}]`);

// One stock's record from its listing row (or null when the listing fetch failed)
function buildStock(symbol, row, previous, pricesAsOf) {
  const info = STOCK_INFO[symbol];
  const base = { symbol, name: info.name, sector: info.sector };
  if (!row || row.price == null) {
    return previous ? { ...previous, ...base, stale: true, staleSince: previous.staleSince || previous.pricesAsOf || null } : null;
  }
  // Add today's close to the history when the stock traded (the source's history only has
  // traded days)
  let history = readHistory(symbol);
  if (pricesAsOf && row.volume) {
    history = mergeHistory(history, [[nairobiDate(pricesAsOf), row.price]]);
    writeHistory(symbol, history);
  }
  return {
    ...base,
    price: row.price,
    change: row.change,
    changePercent: row.changePercent,
    volume: row.volume,
    suspended: row.suspended,
    pricesAsOf,
    oneDay: row.changePercent,
    ...returnsFromHistory(history, row.price),
    news: previous?.news || []
  };
}

async function fetchAll(previous, detailsPerRun) {
  let rows = [];
  let market = previous.market;
  let pricesAsOf = null;
  try {
    const html = await withRetry(() => fetchRaw(afx.listingUrl()));
    rows = afx.parseListing(html);
    pricesAsOf = afx.parseListingTime(html);
    market = { ...afx.parseMarketSummary(html), asOf: pricesAsOf };
    console.log(`Listing: ${rows.length} securities as of ${pricesAsOf}`);
  } catch (err) {
    console.warn(`⚠️  Listing fetch failed: ${err.message} — keeping previous prices (stale)`);
  }
  const bySymbol = Object.fromEntries(rows.map(r => [r.symbol, r]));
  const unknown = rows.filter(r => !STOCK_INFO[r.symbol]).map(r => `${r.symbol} (${r.name})`);
  if (unknown.length) console.warn(`⚠️  Listed but not in data/universe.json: ${unknown.join(', ')}`);

  // Details before building so fresh history feeds today's returns
  if (detailsPerRun > 0) await refreshSomeDetails(STOCKS, detailsPerRun);

  const stocks = {};
  for (const symbol of STOCKS) {
    const s = buildStock(symbol, bySymbol[symbol], previous.stocks[symbol], pricesAsOf);
    if (s) stocks[symbol] = s;
  }

  console.log('Fetching news...');
  for (const symbol of STOCKS) {
    if (!stocks[symbol]) continue;
    const news = await getNews(STOCK_INFO[symbol]);
    if (news) stocks[symbol].news = news;
    await sleep(750);
  }
  return { market, stocks };
}

// Stock record plus its current details, valuation and returns, as the templates use it.
// Returns are recomputed from the history on disk so a render after a backfill (or
// --render-only) matches the charts.
function withDetails(stock) {
  const details = readDetails(stock.symbol);
  const history = readHistory(stock.symbol);
  const returns = history.length ? returnsFromHistory(history, stock.price) : {};
  return { ...stock, ...returns, details, ...valuation(details, stock.price), range52w: range52w(history, stock.price) };
}

// Lowest and highest close over the last 52 weeks, including the current price. Null
// when the history doesn't cover the full year (recent listings, missing backfill).
function range52w(history, price, now = new Date()) {
  const start = monthsAgo(now, 12).toISOString().slice(0, 10);
  if (!history.length || history[0][0] > start) return null;
  const closes = history.filter(r => r[0] >= start).map(r => r[1]);
  if (price != null) closes.push(price);
  return { low: Math.min(...closes), high: Math.max(...closes) };
}

function render(data) {
  const { renderProfile } = require('./templates/profile');
  const { renderSector } = require('./templates/sector');
  const { NAV_CSS, renderNav, renderFooterLinks } = require('./templates/site');
  const { renderHomeHead, renderStaticStocks, renderStaticNews, renderMarketStrip } = require('./templates/home');

  const stocks = Object.fromEntries(Object.entries(data.stocks).map(([s, d]) => [s, withDetails(d)]));
  const sectors = UNIVERSE.sectors;

  // Homepage gets a lighter copy: no descriptions, 3 news items, sparklines
  const homepageData = Object.fromEntries(Object.entries(stocks).map(([symbol, d]) => {
    const { details, news, ...rest } = d;
    return [symbol, { ...rest, news: (news || []).slice(0, 3), spark: sparklines(readHistory(symbol), d.price) }];
  }));
  const sectorInfo = Object.fromEntries(sectors.map(sector => {
    const content = readSectorContent(sector);
    return [sector, { summary: content?.summary || null, url: `${SECTOR_PAGES_DIR}/${sectorSlug(sector)}.html` }];
  }));
  const asOf = data.market?.asOf;
  let indexHTML = fs.readFileSync('index.html', 'utf8');
  const indent = (json) => json.replace(/^/gm, '      ').trim();
  indexHTML = indexHTML
    .replace(/const demoData = \{[\s\S]*?^\s*\};/m, () => `const demoData = ${indent(compactNumberArrays(JSON.stringify(homepageData, null, 2)))};`)
    .replace(/const SECTORS = \[[^\]]*\];/, () => `const SECTORS = ${JSON.stringify(sectors)};`)
    .replace(/const SECTOR_INFO = [\s\S]*?; \/\/ end SECTOR_INFO/, () => `const SECTOR_INFO = ${JSON.stringify(sectorInfo)}; // end SECTOR_INFO`)
    .replace(/<!-- SITE_NAV -->[\s\S]*?<!-- \/SITE_NAV -->/, () => `<!-- SITE_NAV -->\n${renderNav('', sectors, SITE.name, 'dashboard')}\n  <!-- /SITE_NAV -->`)
    .replace(/<!-- SITE_FOOTER -->[\s\S]*?<!-- \/SITE_FOOTER -->/, () => `<!-- SITE_FOOTER -->\n${renderFooterLinks('', sectors, SITE.name)}\n    <!-- /SITE_FOOTER -->`)
    .replace(/\/\* SITE_NAV_CSS \*\/[\s\S]*?\/\* \/SITE_NAV_CSS \*\//, () => `/* SITE_NAV_CSS */${NAV_CSS.replace(/^/gm, '    ')}    /* /SITE_NAV_CSS */`)
    .replace(/<!-- SEO_HEAD -->[\s\S]*?<!-- \/SEO_HEAD -->/, () => `<!-- SEO_HEAD -->\n${renderHomeHead(SITE)}\n  <!-- /SEO_HEAD -->`)
    .replace(/<!-- MARKET_STRIP -->[\s\S]*?<!-- \/MARKET_STRIP -->/, () => `<!-- MARKET_STRIP -->${renderMarketStrip(data.market, Object.values(stocks))}<!-- /MARKET_STRIP -->`)
    .replace(/<!-- STATIC_STOCKS -->[\s\S]*?<!-- \/STATIC_STOCKS -->/, () => `<!-- STATIC_STOCKS -->${renderStaticStocks(Object.values(stocks))}<!-- /STATIC_STOCKS -->`)
    .replace(/<!-- STATIC_NEWS -->[\s\S]*?<!-- \/STATIC_NEWS -->/, () => `<!-- STATIC_NEWS -->${renderStaticNews(Object.values(stocks))}<!-- /STATIC_NEWS -->`)
    .replace(/<!-- DATA_TIME -->[\s\S]*?<!-- \/DATA_TIME -->/, () => `<!-- DATA_TIME -->${dataTimeLabel(asOf)}<!-- /DATA_TIME -->`);
  fs.writeFileSync('index.html', indexHTML);
  console.log('Updated index.html');

  fs.mkdirSync(PAGES_DIR, { recursive: true });
  for (const symbol of STOCKS) {
    if (!stocks[symbol]) continue;
    const peers = STOCKS.filter(s => s !== symbol && stocks[s] && stocks[s].sector === stocks[symbol].sector).map(s => stocks[s]);
    fs.writeFileSync(`${PAGES_DIR}/${symbol.toLowerCase()}.html`,
      renderProfile(stocks[symbol], { sectors, site: SITE, chart: chartSeries(readHistory(symbol)), peers }));
  }
  console.log(`Rendered ${Object.keys(stocks).length} stock pages`);

  fs.mkdirSync(SECTOR_PAGES_DIR, { recursive: true });
  for (const sector of sectors) {
    const members = STOCKS.filter(s => stocks[s] && stocks[s].sector === sector).map(s => stocks[s]);
    fs.writeFileSync(`${SECTOR_PAGES_DIR}/${sectorSlug(sector)}.html`, renderSector(sector, readSectorContent(sector), members, { sectors, site: SITE }));
  }
  console.log(`Rendered ${sectors.length} sector pages`);

  const today = new Date().toISOString().slice(0, 10);
  const pages = ['',
    ...sectors.map(s => `${SECTOR_PAGES_DIR}/${sectorSlug(s)}.html`),
    ...STOCKS.filter(s => stocks[s]).map(s => `${PAGES_DIR}/${s.toLowerCase()}.html`)];
  fs.writeFileSync('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map(p => `  <url><loc>${SITE.url}${p}</loc><lastmod>${today}</lastmod><changefreq>daily</changefreq></url>`).join('\n')}
</urlset>
`);
  fs.writeFileSync('robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${SITE.url}sitemap.xml\n`);
  console.log(`Wrote sitemap.xml (${pages.length} pages) and robots.txt`);

  // Remove generated pages for tickers no longer in the universe
  const current = new Set(STOCKS.map(s => `${s.toLowerCase()}.html`));
  for (const file of fs.readdirSync(PAGES_DIR)) {
    if (!file.endsWith('.html') || current.has(file)) continue;
    if (fs.readFileSync(`${PAGES_DIR}/${file}`, 'utf8').includes(GENERATED_MARKER)) {
      fs.unlinkSync(`${PAGES_DIR}/${file}`);
      console.log(`  Removed ${PAGES_DIR}/${file} (no longer in data/universe.json)`);
    }
  }
}

function readSectorContent(sector) {
  const file = `${SECTOR_DIR}/${sectorSlug(sector)}.json`;
  return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : null;
}

async function main() {
  const args = process.argv.slice(2);
  if (args.includes('--backfill')) {
    // Only tickers without details yet, so an interrupted backfill resumes where it stopped
    const todo = STOCKS.filter(s => !readDetails(s));
    console.log(`Backfilling ${todo.length} ticker(s) (~${Math.ceil(todo.length * 2 * CRAWL_DELAY_MS / 60000)} min)`);
    await refreshSomeDetails(todo, todo.length);
    return;
  }
  const previous = readPreviousData();
  let data = previous;
  if (!args.includes('--render-only')) {
    const n = Number((args.find(a => a.startsWith('--details=')) || '').split('=')[1] ?? DEFAULT_DETAILS_PER_RUN);
    data = await fetchAll(previous, Number.isFinite(n) ? n : DEFAULT_DETAILS_PER_RUN);
    fs.writeFileSync(MARKET_FILE, JSON.stringify(data, null, 2) + '\n');
    console.log(`Wrote ${MARKET_FILE}`);
  } else {
    console.log('Render-only: using data/market.json, no fetching');
  }
  render(data);

  const stale = Object.values(data.stocks).filter(s => s.stale).length;
  console.log(`\n✅ Done: ${Object.keys(data.stocks).length}/${STOCKS.length} stocks${stale ? `, ${stale} stale` : ''}`);
}

if (require.main === module) {
  main().catch(err => {
    console.error('Fatal error:', err);
    process.exit(1);
  });
}

// Exported for tests
module.exports = {
  returnsFromHistory, mergeHistory, range52w, sparklines, chartSeries, downsample, valuation,
  pickDetailTickers, parseGoogleNews, cleanNewsTitle, isLowValueNews, newsQuery,
  nairobiDate, dataTimeLabel, compactNumberArrays, RETURN_PERIODS
};
