const test = require('node:test');
const assert = require('node:assert');

const { renderProfile, formatKes, escapeHtml } = require('../templates/profile');
const { renderSector, sectorStats } = require('../templates/sector');
const { renderMarketStrip } = require('../templates/home');

const SITE = { name: 'Test Digest', url: 'https://example.com/' };
const stock = {
  symbol: 'SCOM', name: 'Safaricom Plc', sector: 'Telecommunication', price: 36.2, change: -0.4, changePercent: -1.09,
  volume: 2.5e6, oneDay: -1.09, ytd: 27.7, oneYear: 25.7, pe: 15.2, dividendYield: 6.4, marketCap: 1.45e12,
  details: { description: 'Telco <b>& M-PESA</b>', eps: 2.39, dps: 2.3, sharesOutstanding: 40.1e9, website: 'www.safaricom.co.ke' },
  news: [{ title: 'Profit up', source: 'Business Daily', date: '2026-09-22T08:00:00Z', url: 'https://example.com/n' }]
};

test('renderProfile escapes scraped text and shows valuation', () => {
  const html = renderProfile(stock, { sectors: ['Telecommunication'], site: SITE, chart: { daily: [['2026-09-22', 36.6]], weekly: [] }, peers: [] });
  assert.match(html, /<!-- Generated by update-stocks.js/);
  assert.match(html, /Telco &lt;b&gt;&amp; M-PESA&lt;\/b&gt;/);
  assert.match(html, /KES 36\.20/);
  assert.match(html, /15\.2×/);
  assert.match(html, /6\.4%/);
  assert.match(html, /href="https:\/\/example.com\/stocks\/scom.html"/);
  assert.match(html, /\.\.\/sectors\/telecommunication\.html/);
});

test('renderProfile flags suspended and stale stocks', () => {
  const html = renderProfile({ ...stock, suspended: true, stale: true, staleSince: '2026-09-20T12:00:00Z' }, { site: SITE });
  assert.match(html, /Trading in this security is suspended/);
  assert.match(html, /couldn't be refreshed/);
});

test('renderSector lists members by market cap with sector stats', () => {
  const other = { ...stock, symbol: 'AIR', name: 'Airtel', marketCap: 1e9, pe: 5, dividendYield: 0 };
  const html = renderSector('Telecommunication', null, [other, stock], { sectors: ['Telecommunication'], site: SITE });
  assert.ok(html.indexOf('stocks/scom.html') < html.indexOf('stocks/air.html'));
  const stats = sectorStats([other, stock]);
  assert.strictEqual(stats.count, 2);
  assert.strictEqual(stats.medianPe, 10.1);
  assert.strictEqual(stats.medianYield, 6.4); // non-payers excluded
});

test('formatKes and renderMarketStrip', () => {
  assert.strictEqual(formatKes(1.45e12), 'KES 1.45T');
  assert.strictEqual(formatKes(820.3e9), 'KES 820.3B');
  assert.strictEqual(formatKes(null), '—');
  assert.strictEqual(renderMarketStrip(null, []), '');
  assert.match(renderMarketStrip({ nasi: 247.21, nasiChangePercent: -0.22, nasiYtdPercent: 32.5, marketCap: 4.19e12 }, [stock]), /247\.21/);
  assert.strictEqual(escapeHtml('a & b'), 'a &amp; b');
});
