// Renders a sector page (sectors/<slug>.html): optional background from
// data/sectors/<slug>.json (summary + sections of trusted HTML), sector summary stats,
// a comparison table of every stock in the sector, and combined news.

const { sectorSlug } = require('../lib/sectors');
const {
  formatKes, formatPrice, formatPct, pctColor, formatRatio, formatYield, formatDate, escapeHtml, CSS, DISCLAIMER
} = require('./profile');
const { NAV_CSS, renderNav, renderFooterLinks, seoTags } = require('./site');

const median = (values) => {
  const v = values.filter(x => x != null).sort((a, b) => a - b);
  if (!v.length) return null;
  const mid = Math.floor(v.length / 2);
  return v.length % 2 ? v[mid] : (v[mid - 1] + v[mid]) / 2;
};

// Sector totals and medians shown above the table
function sectorStats(stocks) {
  const caps = stocks.map(s => s.marketCap).filter(v => v != null);
  return {
    count: stocks.length,
    marketCap: caps.length ? caps.reduce((a, b) => a + b, 0) : null,
    medianPe: median(stocks.map(s => s.pe)),
    medianYield: median(stocks.map(s => s.dividendYield).filter(v => v > 0))
  };
}

function renderSector(sector, content, stocks, opts = {}) {
  const { sectors = [], site = {} } = opts;
  const slug = sectorSlug(sector);
  const plain = (s) => String(s || '').replace(/<[^>]+>/g, '');
  const description = plain(content?.summary) ||
    `${sector} stocks on the Nairobi Securities Exchange: share prices, returns, P/E ratios, dividend yields and news.`;
  // Suspended counters last; they can't be traded
  const byCap = [...stocks].sort((a, b) => (Boolean(a.suspended) - Boolean(b.suspended)) || (b.marketCap ?? -1) - (a.marketCap ?? -1));
  const stats = sectorStats(stocks);

  const background = content
    ? `    <div class="section science">
      <h2>About the Sector</h2>
${(content.sections || []).map(sec => `      <h3>${sec.heading}</h3>\n      ${sec.body}`).join('\n')}
      <div class="meta-line">Last reviewed ${formatDate(content.reviewed)}. General educational content, not a recommendation.</div>
    </div>`
    : '';

  const rows = byCap.map(s => `          <tr>
            <td><a href="../stocks/${s.symbol.toLowerCase()}.html">${s.symbol}</a></td>
            <td>${escapeHtml(s.name)}${s.suspended ? ' <span class="item-meta">(suspended)</span>' : ''}</td>
            <td class="num">${formatPrice(s.price)}</td>
            <td class="num" style="color: ${pctColor(s.oneDay)}">${formatPct(s.oneDay)}</td>
            <td class="num" style="color: ${pctColor(s.ytd)}">${formatPct(s.ytd)}</td>
            <td class="num" style="color: ${pctColor(s.oneYear)}">${formatPct(s.oneYear)}</td>
            <td class="num">${formatKes(s.marketCap)}</td>
            <td class="num">${formatRatio(s.pe)}</td>
            <td class="num">${formatYield(s.dividendYield)}</td>
          </tr>`).join('\n');

  const byUrl = new Map();
  for (const s of stocks) {
    for (const n of s.news || []) {
      if (!n.url) continue;
      if (!byUrl.has(n.url)) byUrl.set(n.url, { ...n, tickers: [] });
      byUrl.get(n.url).tickers.push(s.symbol);
    }
  }
  const news = [...byUrl.values()].sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 15);

  return `<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(sector)} Stocks on the NSE | ${escapeHtml(site.name)}</title>
  <meta name="description" content="${escapeHtml(description.slice(0, 300))}">
  <meta property="og:title" content="${escapeHtml(sector)} Stocks on the Nairobi Securities Exchange">
  <meta property="og:description" content="${escapeHtml(description.slice(0, 300))}">
  <meta property="og:type" content="article">
${seoTags(site, `sectors/${slug}.html`)}
  <style>
${(CSS + NAV_CSS).replace(/^/gm, '    ').replace(/^\s+$/gm, '')}
  </style>
</head>

<body>
  <!-- Generated by update-stocks.js from data/sectors and live market data. Do not edit by hand. -->
${renderNav('../', sectors, escapeHtml(site.name), 'sectors')}

  <header>
    <div>
      <h1>${escapeHtml(sector)}</h1>
      <div>${stats.count} NSE-listed ${stats.count === 1 ? 'security' : 'securities'}</div>
    </div>
  </header>

  <div class="container">

${content?.summary ? `    <div class="section">\n      <p class="para">${content.summary}</p>\n    </div>\n\n` : ''}    <div class="section">
      <h2>Sector at a Glance</h2>
      <div class="summary-stats">
        <div class="card"><div class="card-subtitle">Listed</div><div class="card-value">${stats.count}</div></div>
        <div class="card"><div class="card-subtitle">Combined Market Cap</div><div class="card-value">${formatKes(stats.marketCap)}</div></div>
        <div class="card"><div class="card-subtitle">Median P/E</div><div class="card-value">${formatRatio(stats.medianPe)}</div></div>
        <div class="card"><div class="card-subtitle">Median Yield (payers)</div><div class="card-value">${formatYield(stats.medianYield)}</div></div>
      </div>
    </div>

    <div class="section">
      <h2>Companies</h2>
      <div style="overflow-x: auto;">
      <table>
        <thead>
          <tr><th>Ticker</th><th>Company</th><th class="num">Price (KES)</th><th class="num">1D</th><th class="num">YTD</th><th class="num">1Y</th><th class="num">Mkt Cap</th><th class="num">P/E</th><th class="num">Yield</th></tr>
        </thead>
        <tbody>
${rows}
        </tbody>
      </table>
      </div>
      <p class="note">Sorted by market cap. P/E and yield use the latest reported EPS and dividend per share against today's price.</p>
    </div>

${background ? background + '\n\n' : ''}    <div class="section">
      <h2>Sector News</h2>
${news.length ? `      <ul class="item-list">
${news.map(n => `        <li><a href="${escapeHtml(n.url)}" target="_blank" rel="noopener">${escapeHtml(n.title)}</a><div class="item-meta">${n.tickers.join(', ')} · ${escapeHtml(n.source)} · ${formatDate(n.date)}</div></li>`).join('\n')}
      </ul>` : '      <p class="note">No recent news.</p>'}
    </div>

  </div>

  <footer class="disclaimer">
${renderFooterLinks('../', sectors, escapeHtml(site.name))}
    <p>${DISCLAIMER}</p>
  </footer>

</body>

</html>
`;
}

module.exports = { renderSector, sectorStats, median };
